#!/bin/sh

if test "$REQUEST_METHOD" = "POST"; then
	chords_path=$DOCUMENT_ROOT/items/chords/items
	ids="`qhash -l $chords_path/index.db | id_query p :1`"
	qhash -m1 $ids $ITEM_PATH/songs.db
	qhash -p"$REMOTE_USER" $ITEM_PATH/members.db
	cat > $ITEM_PATH/format <<!
Entrada
Aleluia
Ofertório
Santo
Comunhão
Ação de Graças
Saída
!
fi
