#!/bin/sh

if test "$REQUEST_METHOD" = "POST"; then
	chords_path=$DOCUMENT_ROOT/items/chords/items
	cp $chords_path/index $ITEM_PATH/songs.db
	cat > $ITEM_PATH/format <<!
Entrada
Aleluia
Ofertório
Santo
Comunhão
Ação de Graças
Saída
!
fi
