#!/bin/sh

chords_path=$DOCUMENT_ROOT/items/chords/items

list() {
	$qdb -l songs.db:s | while read link flags name; do
		echo "<a href='/chords/$link/'>$name</a>"
	done
}

AddForm() {
	im "$OWNER" "$iid" || return 0
	title="$iid `cat counter`"
	local _add="`_ add`"
	buttons="$buttons`RB + "$_add" "/sb/add?choir=$iid&title=$title"`"
}

AddForm
echo "$buttons" >> $DOCUMENT_ROOT/tmp/fun

show_members() {
	groups | grep -q $iid || return 0
	cat <<!
<h4>`_ Members`</h4>
<pre>`getent group $iid | tr ':' ' ' | awk '{ print $4 }' | tr ',' '\n'`</pre>
!
}

cat <<!
<h4>`_ Format`</h4>
<pre>
`cat format`
</pre>
`show_members`
<h4>`_ Songs`</h4>
<pre>`list`</pre>
!
